disparity_filter.enable: true
spatial_filter.enable: true
spatial_filter.filter_magnitude: 5
spatial_filter.filter_smooth_alpha: 0.75
spatial_filter.filter_smooth_delta: 1
spatial_filter.holes_fill: 4

temporal_filter.enable: true
temporal_filter.filter_smooth_alpha: 0.6
temporal_filter.filter_smooth_delta: 20